# Generated by Django 2.2.16 on 2020-10-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetasapp', '0002_auto_20201020_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iniciar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.TextField(max_length=30)),
                ('clave', models.TextField(max_length=20)),
            ],
        ),
    ]
