# Generated by Django 2.2.16 on 2020-11-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetasapp', '0003_iniciar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contraseña',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contraseña1', models.TextField(max_length=20)),
                ('contraseña2', models.TextField(max_length=20)),
            ],
        ),
    ]
