# Generated by Django 2.2.16 on 2020-11-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetasapp', '0004_contraseña'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=50)),
                ('advertencia', models.TextField(max_length=40)),
                ('ingrdientes', models.TextField(max_length=200)),
                ('intrucciones', models.TextField(max_length=450)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
