# Generated by Django 2.2.16 on 2020-11-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetasapp', '0005_receta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='ingrdientes',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='receta',
            name='intrucciones',
            field=models.TextField(max_length=1050),
        ),
    ]
